<<<<<<< HEAD
main_homepage:
    path:     /site
    defaults: { _controller: MainBundle:Default:index }
=======
main_home:
    path:     /site
    defaults: { _controller: MainBundle:Main:index }
>>>>>>> abe0793156f1fa6f6e9f80e1299f81ef63031576
